"""create conversations and chat messages

Revision ID: 1e4e3aeb617b
Revises: 519c92e10a8b
Create Date: 2026-09-03 00:37:49.841264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e4e3aeb617b'
down_revision: Union[str, Sequence[str], None] = '519c92e10a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_documents_asset_id'), table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_embedding_hnsw'), table_name='vector_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_vector_documents_metadata_gin'), table_name='vector_documents', postgresql_using='gin')
    op.drop_table('vector_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_documents',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('vector_documents_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_documents_pkey'))
    )
    op.create_index(op.f('ix_vector_documents_metadata_gin'), 'vector_documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vector_documents_embedding_hnsw'), 'vector_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_vector_documents_asset_id'), 'vector_documents', ['asset_id'], unique=False)
    # ### end Alembic commands ###
