"""update models for parsing and semantic chunks

Revision ID: 407bc812da97
Revises: 089579f210f1
Create Date: 2026-08-16 23:10:59.097802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '407bc812da97'
down_revision: Union[str, Sequence[str], None] = '089579f210f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_documents_asset_id'), table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_embedding_hnsw'), table_name='vector_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_vector_documents_metadata_gin'), table_name='vector_documents', postgresql_using='gin')
    op.drop_table('vector_documents')
    op.add_column('assets', sa.Column('document_name', sa.String(length=255), nullable=False))
    op.add_column('assets', sa.Column('file_checksum', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('total_pages', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False))
    op.add_column('assets', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('assets', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default='PENDING',
               existing_nullable=False)
    op.create_index(op.f('ix_assets_document_name'), 'assets', ['document_name'], unique=False)
    op.create_unique_constraint('uq_assets_project_checksum', 'assets', ['project_id', 'file_checksum'])
    op.add_column('chunks', sa.Column('chunk_id', sa.String(length=50), nullable=False))
    op.add_column('chunks', sa.Column('document_name', sa.String(length=255), nullable=False))
    op.add_column('chunks', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('chunks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chunks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('chunks', 'section_title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               server_default='0',
               nullable=False)
    op.drop_index(op.f('ix_chunks_chunk_uuid'), table_name='chunks')
    op.create_index('ix_chunks_asset_page', 'chunks', ['asset_id', 'page_number'], unique=False)
    op.create_index('ix_chunks_asset_section', 'chunks', ['asset_id', 'section_title'], unique=False)
    op.create_index(op.f('ix_chunks_document_name'), 'chunks', ['document_name'], unique=False)
    op.create_unique_constraint('uq_chunks_asset_chunk_id', 'chunks', ['asset_id', 'chunk_id'])
    op.create_check_constraint('ck_chunks_chunk_index_positive', 'chunks', 'chunk_index > 0')
    op.create_check_constraint('ck_chunks_page_number_positive', 'chunks', 'page_number > 0')
    op.create_check_constraint('ck_chunks_token_count_non_negative', 'chunks', 'token_count >= 0')
    op.drop_column('chunks', 'chunk_text')
    op.drop_column('chunks', 'chunk_uuid')
    op.add_column('projects', sa.Column('source_version', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('license_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default='ACTIVE',
               existing_nullable=False)
    op.drop_column('projects', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'license_name')
    op.drop_column('projects', 'source_version')
    op.add_column('chunks', sa.Column('chunk_uuid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('ck_chunks_token_count_non_negative', 'chunks', type_='check')
    op.drop_constraint('ck_chunks_page_number_positive', 'chunks', type_='check')
    op.drop_constraint('ck_chunks_chunk_index_positive', 'chunks', type_='check')
    op.drop_constraint('uq_chunks_asset_chunk_id', 'chunks', type_='unique')
    op.drop_index(op.f('ix_chunks_document_name'), table_name='chunks')
    op.drop_index('ix_chunks_asset_section', table_name='chunks')
    op.drop_index('ix_chunks_asset_page', table_name='chunks')
    op.create_index(op.f('ix_chunks_chunk_uuid'), 'chunks', ['chunk_uuid'], unique=True)
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'section_title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('chunks', 'updated_at')
    op.drop_column('chunks', 'created_at')
    op.drop_column('chunks', 'metadata')
    op.drop_column('chunks', 'page_end')
    op.drop_column('chunks', 'chunk_index')
    op.drop_column('chunks', 'text')
    op.drop_column('chunks', 'document_name')
    op.drop_column('chunks', 'chunk_id')
    op.drop_constraint('uq_assets_project_checksum', 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_document_name'), table_name='assets')
    op.alter_column('assets', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'parsed_at')
    op.drop_column('assets', 'total_chunks')
    op.drop_column('assets', 'total_pages')
    op.drop_column('assets', 'error_message')
    op.drop_column('assets', 'file_checksum')
    op.drop_column('assets', 'document_name')
    op.create_table('vector_documents',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('vector_documents_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_documents_pkey'))
    )
    op.create_index(op.f('ix_vector_documents_metadata_gin'), 'vector_documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vector_documents_embedding_hnsw'), 'vector_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_vector_documents_asset_id'), 'vector_documents', ['asset_id'], unique=False)
    # ### end Alembic commands ###
